# sample round config
# all endowments can be specified either as a single number or a list of endowments, one for each player in each group
# if an endowment list is shorter than the number of players in the group, endowments wrap back around to the beginning

# number of players in each group or null if there's only one group
players_per_group: null
# starting cash endowment for each player
cash_endowment: 20
# the amount of the endowment which is a loan
loan_value: 10
# whether or not players are allowed to have negative available cash
allow_short_cash: true
# the amount of cash that players are allowed to borrow when short selling
short_limit_cash: 10
# the length of the round in seconds
period_length: 120
# a multiplier used to change the way currency is displayed to players.
# prices are integers, so all prices are divided by this number before being shown to players.
# a scale of 1000 means that the smallest price a player can enter is 1/1000 or 0.001.
# this should be a power of 10. it'd probably do weird things if it wasn't
currency_scale: 1000
# whether or not arbitrage bots are enabled
bots_enabled: true
# the round which is counted for final payoff
pay_round: 2

# this field lists all the possible states and their relative probability of occuring.
# the probability for each state is calculated as that state's prob_weight divided by
# the sum of prob_weight across all states
states:
  X:
    prob_weight: 1
  Y:
    prob_weight: 2
  Z:
    prob_weight: 3

# this field describes the asset structure for the round
asset_structure:
  # name of the asset
  A:
    # whether the player be allowed to hold negative quantities of this asset
    allow_short: true
    # the maximum amount of this asset a player is allowed to borrow for short selling
    # only specified when allow_short is true
    short_limit: 10
    # whether or not this is an etf asset
    is_etf: false
    # initial endowment of this asset
    endowment: [1, 2]
    # the state-dependent payoffs for this asset
    # only specified when asset ISN'T an etf
    payoffs:
      X: 2
      Y: 1
      Z: 0
  B:
    allow_short: true
    short_limit: 10
    is_etf: false
    endowment: [1, 4]
    payoffs:
      X: 0
      Y: 2
      Z: 1
  C:
    allow_short: false
    is_etf: false
    endowment: 5
    payoffs:
      X: 10
      Y: 0
      Z: 2
  
